### ISSUE TITLE
Having a little trouble with the bot.

### ISSUE THREAD

**Issue by GaryMatthews** [MLP-VectorClub/Muffins#1]
Just having a play with discord and possible use of bots. after a bit of a struggle i managed to get it online. unfortunately seam to be having issues. 
```

[2019-12-02 19:12:15.446] [INFO]   ~ Ready ~
[2019-12-02 19:12:47.761] [LOG]    XXX#XXXX ran !help from #general (M#XXXXXXXXXXXXX)
[2019-12-02 19:12:47.790] [LOG]    null
[2019-12-02 19:12:47.791] [ERROR]  (node:29668) DeprecationWarning: Collection#exists: use Collection#some instead
[2019-12-02 19:12:47.792] [ERROR]  (node:29668) DeprecationWarning: Collection#find: pass a function instead
[2019-12-02 19:12:47.792] [ERROR]  TypeError: Cannot read property 'constructor' of null
    at Server.mention (xxxxxxxxx/classes/Server.js:689:58)
    at Object.<anonymous> (xxxxxxxxx/commands/casual.js:9:68)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at fs.readdirSync.forEach.file (xxxxxxxxx/commands/help.js:55:14)
```

**Comment by SeinopSys** [comment]
Are you sure you posted this to the right repository? This is not a Discord bot so you would be running into a heck of a lot of issues trying to run it as one.

**Comment by GaryMatthews** [comment]
yeah look sorry i dunno how i made that mistake :) 

juggling so many diff projects and repos i am having trouble keeping track of them all...

**Comment by GaryMatthews** [comment]
should have sent this to PennyCurve repo :p
